/**
 * 共有リンクの相手の画面だけの文言（日本語と英語）。録画の帯（FeedbackToolbar）の文言は、アプリの i18n（@shared/i18n）をそのまま使う。
 */
const ja = {
  loading: '読み込んでいます…',
  notFound: 'この共有は見つかりません。リンクを確かめてください。',
  gone: 'この共有は期限が切れました（共有は7日で消えます）。',
  failed: 'うまくいきませんでした。時間をおいてもう一度試してください。',
  locked: 'この共有にはパスワードが付いています',
  lockedHint: '共有した人から別に伝えられたパスワードを入れてください。',
  password: 'パスワード',
  unlock: '開く',
  wrongPassword: 'パスワードが違います。',
  rateLimited: '試す回数が多すぎます。少し待ってからもう一度試してください。',
  everyone: 'このリンクを持つ人は誰でも、届いた指摘と録画を見られます。',
  expires: '{date} に消えます',
  name: '名前（任意）',
  namePlaceholder: '指摘に付く名前',
  start: '指摘する',
  live: 'このページを開いて録画',
  liveDesc: 'ページを触りながら、ペン・枠・文字と声で指摘します。',
  liveAudioOnly: 'このブラウザでは画面は録れません。声と書き込みを送ります（Chrome・Edge なら画面も録れます）。',
  screen: '画面を共有して録画',
  screenDesc: '別のタブ・ウインドウ・アプリ・画面全体を録ります。',
  upload: '画面収録の動画を送る',
  uploadDesc: 'スマホの画面収録などの動画（10分・300MB まで）を送ります。',
  noScreenShare: 'このブラウザは画面共有に対応していません。',
  received: '届いた指摘',
  none: 'まだ届いていません。',
  anonymous: '名前なし',
  play: '再生',
  close: '閉じる',
  memo: 'メモ',
  copy: 'コピー',
  copied: 'コピーしました',
  copyAll: 'すべてコピー',
  memoLocked: 'メモはパスワードで暗号化されています。パスワードを入れると表示します。',
  show: '表示',
  consentTitle: '録画して送る前に',
  consentRecorded: '画面・声・書き込み・文字の指摘を録画して、この共有に送ります。',
  consentVisible: 'このリンクを持つ人は誰でも、送った内容（名前を含む）を見られます。',
  consentDeleted: '送った内容は {date} に消えます（7日）。',
  consentScreen: '画面共有では、選んだ画面に映るもの（通知・ほかのウインドウを含む）がすべて録画されます。見せたくないものは閉じてから選んでください。',
  consentLiveTab: '次の画面で「このタブ」を選ぶと、ページの部分だけを録画します。',
  consentStart: '同意して始める',
  cancel: 'やめる',
  micDenied: 'マイクが使えないため、声は録りません。',
  captureDenied: '画面を録れなかったため、声と書き込みだけを録ります。',
  frameBlocked: 'ページが表示されないときは「画面を共有して録画」を使ってください（サイトが埋め込みを断っています）。',
  openTab: '新しいタブで開く',
  reviewTitle: '録画を送りますか？',
  duration: '長さ {time}',
  notes: '文字の指摘 {count} 件',
  send: '送る',
  retake: '撮り直す',
  discard: '送らずに戻る',
  sending: '送っています… {percent}%',
  sent: '送りました。ありがとうございます。',
  back: '一覧へ戻る',
  tooLarge: '大きすぎます（10分・300MB まで）。',
  tooLong: '長すぎます（10分まで）。',
  badMedia: 'この形式の動画は送れません（MP4・MOV・WebM）。',
  pickFile: '動画を選ぶ',
  comment: 'コメント（任意）',
  limitReached: '録画の上限（10分・300MB）に達したので止めました。',
  memoNotice: '共有した人からのメモ',
  noteLabelPlaceholder: '直してほしいことを書いてください',
  noteLabelHint: 'Enter で追加・Shift+Enter で改行・Esc で取り消し',
  noteLabelAdd: '追加',
  modeLive: 'ライブ',
  modeScreen: '画面共有',
  modeUpload: '動画',
  modeNotes: '文字',
  noVideo: '声と書き込み'
}

type Strings = typeof ja

const en: Strings = {
  loading: 'Loading…',
  notFound: 'This share link was not found. Check the link.',
  gone: 'This share link has expired (shares are deleted after 7 days).',
  failed: 'Something went wrong. Please try again later.',
  locked: 'This share is protected by a password',
  lockedHint: 'Enter the password the sender gave you separately.',
  password: 'Password',
  unlock: 'Open',
  wrongPassword: 'Wrong password.',
  rateLimited: 'Too many attempts. Wait a little and try again.',
  everyone: 'Anyone with this link can see the feedback and recordings sent here.',
  expires: 'Deleted on {date}',
  name: 'Name (optional)',
  namePlaceholder: 'Shown with your feedback',
  start: 'Give feedback',
  live: 'Open the page and record',
  liveDesc: 'Use the page while pointing things out with the pen, box, text and your voice.',
  liveAudioOnly: 'This browser cannot record the screen here, so your voice and marks are sent (Chrome and Edge also record the screen).',
  screen: 'Share your screen and record',
  screenDesc: 'Record another tab, a window, an app or your whole screen.',
  upload: 'Send a screen recording',
  uploadDesc: 'Send a video such as a phone screen recording (up to 10 minutes, 300 MB).',
  noScreenShare: 'This browser cannot share the screen.',
  received: 'Feedback received',
  none: 'Nothing yet.',
  anonymous: 'Anonymous',
  play: 'Play',
  close: 'Close',
  memo: 'Memo',
  copy: 'Copy',
  copied: 'Copied',
  copyAll: 'Copy all',
  memoLocked: 'The memo is encrypted with the password. Enter the password to show it.',
  show: 'Show',
  consentTitle: 'Before you record',
  consentRecorded: 'Your screen, voice, marks and typed notes are recorded and sent to this share.',
  consentVisible: 'Anyone with this link can see what you send, including your name.',
  consentDeleted: 'What you send is deleted on {date} (after 7 days).',
  consentScreen: 'Screen sharing records everything shown on the screen you pick, including notifications and other windows. Close anything private before you pick.',
  consentLiveTab: 'On the next screen, pick "This tab" to record only the page area.',
  consentStart: 'Agree and start',
  cancel: 'Cancel',
  micDenied: 'The microphone is not available, so your voice is not recorded.',
  captureDenied: 'The screen could not be recorded, so only your voice and marks are recorded.',
  frameBlocked: 'If the page does not show, use "Share your screen and record" (the site refuses to be embedded).',
  openTab: 'Open in new tab',
  reviewTitle: 'Send this recording?',
  duration: 'Length {time}',
  notes: 'Typed notes: {count}',
  send: 'Send',
  retake: 'Record again',
  discard: 'Back without sending',
  sending: 'Sending… {percent}%',
  sent: 'Sent. Thank you!',
  back: 'Back to the list',
  tooLarge: 'Too large (up to 10 minutes, 300 MB).',
  tooLong: 'Too long (up to 10 minutes).',
  badMedia: 'This video format cannot be sent (MP4, MOV or WebM).',
  pickFile: 'Choose a video',
  comment: 'Comment (optional)',
  limitReached: 'Stopped at the recording limit (10 minutes, 300 MB).',
  memoNotice: 'Memo from the sender',
  noteLabelPlaceholder: 'What should change here?',
  noteLabelHint: 'Enter to add · Shift+Enter for a new line · Esc to cancel',
  noteLabelAdd: 'Add',
  modeLive: 'Live',
  modeScreen: 'Screen',
  modeUpload: 'Video',
  modeNotes: 'Text',
  noVideo: 'Voice and marks'
}

export type StringKey = keyof Strings

export const pageLocale: 'ja' | 'en' = (typeof navigator !== 'undefined' && (navigator.language || '').toLowerCase().startsWith('ja')) ? 'ja' : 'en'

const dict: Strings = pageLocale === 'ja' ? ja : en

export function s(key: StringKey, params: Record<string, string | number> = {}): string {
  return dict[key].replace(/\{(\w+)\}/g, (whole, name: string) => (params[name] !== undefined ? String(params[name]) : whole))
}

export function formatDuration(ms: number): string {
  const total = Math.max(0, Math.round(ms / 1000))
  return `${String(Math.floor(total / 60)).padStart(2, '0')}:${String(total % 60).padStart(2, '0')}`
}

export function formatDate(iso: string): string {
  const d = new Date(iso)
  return Number.isNaN(d.getTime()) ? iso : d.toLocaleString(pageLocale === 'ja' ? 'ja-JP' : 'en-US', { dateStyle: 'medium', timeStyle: 'short' })
}
