import { SETTINGS_SCHEMA, STATE_KEYS, type JsonSchema } from './settingsSchema'

/**
 * コーディングエージェント（Claude Code・Codex）に入れる「Ferret の設定を変える」skill。
 * 利用者が Agent に「Ferret でこうしたい」と頼めば、Agent が settings.json を正しい範囲（全体／プロジェクト）で書き換える。
 *
 * 中身は settings.json の JSON Schema（SETTINGS_SCHEMA）から作るので、設定の項目が増えれば skill も合わせて変わる。
 * Ferret が書いた skill には印（SKILL_MARKER）を入れ、印のあるものだけを書き直す（利用者が自分で置いた同名の skill は上書きしない）。
 * Electron に依存しない純粋な処理だけを置く（書き込みは src/main/agentSkill.ts）。
 */

export const AGENT_SKILL_NAME = 'ferret-settings'

/** skill を入れられる Agent。どちらも <設定のフォルダ>/skills/<名前>/SKILL.md を読む */
export const AGENT_SKILL_AGENTS = ['claude', 'codex'] as const
export type AgentSkillAgent = (typeof AGENT_SKILL_AGENTS)[number]

/** Ferret が書いた印。この行があるものだけを Ferret のものとして書き直す */
export const SKILL_MARKER = '<!-- ferret-settings-skill: generated by Ferret. Ferret rewrites this file when its settings change; local edits are overwritten. -->'

export function isFerretSkill(text: string): boolean {
  return text.includes(SKILL_MARKER)
}

export interface AgentSkillStatus {
  agent: AgentSkillAgent
  /** SKILL.md の場所 */
  path: string
  /** Agent の設定のフォルダ（~/.claude など）があるか。無ければその Agent は使っていないとみなす */
  agentDirExists: boolean
  /** Ferret が入れた skill があるか */
  installed: boolean
  /** 同じ名前で Ferret のものでない skill がある（上書きしない） */
  foreign: boolean
  /** 入れた skill がいまの設定の項目と同じ中身か */
  upToDate: boolean
}

/** Agent の設定のフォルダ。CLAUDE_CONFIG_DIR / CODEX_HOME があればそちら（Agent 自身と同じ決まり） */
export function agentConfigDir(agent: AgentSkillAgent, env: Record<string, string | undefined>, home: string, join: (...parts: string[]) => string): string {
  if (agent === 'claude') return env.CLAUDE_CONFIG_DIR?.trim() || join(home, '.claude')
  return env.CODEX_HOME?.trim() || join(home, '.codex')
}

export function agentSkillPath(agent: AgentSkillAgent, env: Record<string, string | undefined>, home: string, join: (...parts: string[]) => string): string {
  return join(agentConfigDir(agent, env, home, join), 'skills', AGENT_SKILL_NAME, 'SKILL.md')
}

export interface SkillContext {
  /** settings.json の絶対パス（配布版は ~/.ferret/settings.json、開発版は ~/.ferret/dev/settings.json など） */
  settingsPath: string
  /** settings.schema.json の絶対パス（Ferret が起動のたびに書き直す） */
  schemaPath: string
  /** 作った Ferret の版 */
  version: string
  schema?: JsonSchema
}

/** 1行に収めた説明（表の中で崩れないよう、改行と | を外す） */
function oneLine(text: string | undefined): string {
  return (text ?? '').replace(/\s+/g, ' ').replace(/\|/g, '/').trim()
}

function typeOf(schema: JsonSchema): string {
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(' / ')
  const type = Array.isArray(schema.type) ? schema.type.join(' or ') : schema.type ?? 'any'
  return type === 'array' && schema.items?.type ? `array of ${schema.items.type}` : type
}

function rows(properties: Record<string, JsonSchema>, prefix: string, skip: ReadonlySet<string> = new Set()): string[] {
  return Object.entries(properties)
    .filter(([key]) => !skip.has(key))
    .map(([key, value]) => `| \`${prefix}${key}\` | ${typeOf(value)} | ${oneLine(value.description)} |`)
}

/** SKILL.md の本文。Agent が読む文なので英語（スキーマの説明も英語） */
export function renderAgentSkill(context: SkillContext): string {
  const schema = context.schema ?? SETTINGS_SCHEMA
  const top = schema.properties ?? {}
  const project = top.projects?.items?.properties ?? {}
  const target = project.urls?.items?.properties ?? {}
  // $schema は道具の印、projects はプロジェクトの範囲として別に書く。状態（state.json）は settings.json に無い
  const globalRows = rows(top, '', new Set(['$schema', 'projects', ...STATE_KEYS]))
  const projectRows = rows(project, 'projects[].', new Set(['urls']))
  const targetRows = rows(target, 'projects[].urls[].')

  return `---
name: ${AGENT_SKILL_NAME}
description: Change settings of Ferret, the voice-and-annotation review app the user runs next to you (theme, language, layout, agents, recording, transcription, organizing, decision model, projects and their review targets such as URLs, launch commands and desktop/mobile/game windows). Use when the user asks to configure, change, turn on/off, add or remove anything "in Ferret", or to register a URL, app window, simulator or launch command for a project.
---

${SKILL_MARKER}
<!-- Ferret ${context.version} -->

# Ferret settings

Ferret keeps all of its configuration in one JSON file and reloads it live: save the file and the app applies the change within a second. You never need to restart Ferret.

- Settings file: \`${context.settingsPath}\`
- JSON Schema (rewritten by Ferret on every start, always matches the running version): \`${context.schemaPath}\`

## Decide the scope first

Every request is either **global** (the whole app, every project) or **project** (only one registered project). Pick the scope before editing:

1. If the user says "this project", "here", "for <project name>", or the change is about a project's URL, launch command, window, kind or name → **project scope**.
2. Otherwise → **global scope**.
3. If the user asks for a project-only version of something that only exists globally (for example "dark theme only in this project"), do not invent a key. Say that the setting is global in Ferret and ask whether to change it for all projects.

### Global scope

Top-level keys of the settings file. Change only the keys you need and keep everything else as is.

| Key | Type | Meaning |
| --- | --- | --- |
${globalRows.join('\n')}

### Project scope

Projects are the objects in the top-level \`projects\` array. Find the right one by \`folderPath\`: the project whose \`folderPath\` is your current working directory or contains it. If none matches, ask the user which project they mean, or add a new entry (\`id\` any unique string, \`folderPath\` absolute path). Never change another project's entry.

| Key | Type | Meaning |
| --- | --- | --- |
${projectRows.join('\n')}

Review targets are \`projects[].urls\` (the first one opens by default). Each needs at least one of \`url\`, \`launchCommand\` or \`windowMatch\`. Use \`windowMatch\` for desktop apps, iOS Simulator, Android Emulator or game editors (Unity, Unreal, Godot): Ferret shows that window live in its editor and records it with voice and annotations.

| Key | Type | Meaning |
| --- | --- | --- |
${targetRows.join('\n')}

## How to edit

1. Read the settings file. If it does not exist yet, create it with only the keys you set (Ferret fills in the defaults).
2. Read the JSON Schema file when you need allowed values, defaults or nested fields that the tables above do not show.
3. Make the smallest change: keep unknown keys, key order and the other projects untouched. Write valid JSON (no comments, no trailing commas).
4. Do not write API keys into the file. Use the \`apiKeyEnv\` fields (the name of an environment variable, or a key in \`~/.ferret/.env\` or the project's \`.env\`), or ask the user to paste the key in Ferret's Settings page.
5. Do not edit \`state.json\` next to the settings file (window state kept by the app).
6. After saving, tell the user what you changed and in which scope. If Ferret rejects the file it shows the error in the app and keeps the previous settings; fix the file using the schema.
`
}
