import { MAX_BROWSER_EXTENSIONS } from './browserExtensions'
import { SETTINGS_SCHEMA, STATE_KEYS, type JsonSchema } from './settingsSchema'

/**
 * コーディングエージェント（Claude Code・Codex）に入れる「Ferret の設定を変える」skill。
 * 利用者が Agent に「Ferret でこうしたい」と頼めば、Agent が settings.json を正しい範囲（全体／プロジェクト）で書き換える。
 *
 * 中身は settings.json の JSON Schema（SETTINGS_SCHEMA）から作るので、設定の項目が増えれば skill も合わせて変わる。
 * Ferret が書いた skill には印（SKILL_MARKER）を入れ、印のあるものだけを書き直す（利用者が自分で置いた同名の skill は上書きしない）。
 * Electron に依存しない純粋な処理だけを置く（書き込みは src/main/agentSkill.ts）。
 */

export const AGENT_SKILL_NAME = 'ferret-settings'

/** skill を入れられる Agent。どちらも <設定のフォルダ>/skills/<名前>/SKILL.md を読む */
export const AGENT_SKILL_AGENTS = ['claude', 'codex'] as const
export type AgentSkillAgent = (typeof AGENT_SKILL_AGENTS)[number]

/** Ferret が書いた印。この行があるものだけを Ferret のものとして書き直す */
export const SKILL_MARKER = '<!-- ferret-settings-skill: generated by Ferret. Ferret rewrites this file when its settings change; local edits are overwritten. -->'

export function isFerretSkill(text: string): boolean {
  return text.includes(SKILL_MARKER)
}

export interface AgentSkillStatus {
  agent: AgentSkillAgent
  /** SKILL.md の場所 */
  path: string
  /** Agent の設定のフォルダ（~/.claude など）があるか。無ければその Agent は使っていないとみなす */
  agentDirExists: boolean
  /** Ferret が入れた skill があるか */
  installed: boolean
  /** 同じ名前で Ferret のものでない skill がある（上書きしない） */
  foreign: boolean
  /** 入れた skill がいまの設定の項目と同じ中身か */
  upToDate: boolean
}

/** Agent の設定のフォルダ。CLAUDE_CONFIG_DIR / CODEX_HOME があればそちら（Agent 自身と同じ決まり） */
export function agentConfigDir(agent: AgentSkillAgent, env: Record<string, string | undefined>, home: string, join: (...parts: string[]) => string): string {
  if (agent === 'claude') return env.CLAUDE_CONFIG_DIR?.trim() || join(home, '.claude')
  return env.CODEX_HOME?.trim() || join(home, '.codex')
}

export function agentSkillPath(agent: AgentSkillAgent, env: Record<string, string | undefined>, home: string, join: (...parts: string[]) => string): string {
  return join(agentConfigDir(agent, env, home, join), 'skills', AGENT_SKILL_NAME, 'SKILL.md')
}

export interface SkillContext {
  /** settings.json の絶対パス（配布版は ~/.ferret/settings.json、開発版は ~/.ferret/dev/settings.json など） */
  settingsPath: string
  /** settings.schema.json の絶対パス（Ferret が起動のたびに書き直す） */
  schemaPath: string
  /** 作った Ferret の版 */
  version: string
  /** 「すべてのプロダクト」（オーケストラ）のフォルダ。human.md・全体の .ferret/costs.json の置き場 */
  editorWorkspacePath?: string
  schema?: JsonSchema
}

/** 1行に収めた説明（表の中で崩れないよう、改行と | を外す） */
function oneLine(text: string | undefined): string {
  return (text ?? '').replace(/\s+/g, ' ').replace(/\|/g, '/').trim()
}

function typeOf(schema: JsonSchema): string {
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(' / ')
  const type = Array.isArray(schema.type) ? schema.type.join(' or ') : schema.type ?? 'any'
  return type === 'array' && schema.items?.type ? `array of ${schema.items.type}` : type
}

/** 型の後ろに添える範囲と既定値（表で値の幅が分かるように） */
function detailsOf(schema: JsonSchema): string {
  const parts: string[] = []
  const { minimum: min, maximum: max } = schema
  if (min !== undefined && max !== undefined) parts.push(`${min}-${max}`)
  else if (min !== undefined) parts.push(`>= ${min}`)
  else if (max !== undefined) parts.push(`<= ${max}`)
  if (schema.default !== undefined && (schema.default === null || typeof schema.default !== 'object')) parts.push(`default ${JSON.stringify(schema.default)}`)
  return parts.length ? ` (${parts.join(', ')})` : ''
}

/**
 * skill に載せない項目。秘密（平文の API キー）は skill から書かせない。
 * アカウント（agentAccounts）は Ferret の Accounts で作ったフォルダと対になるので、中の項目は出さず触らせない
 */
export const SKILL_SECRET_KEYS: ReadonlySet<string> = new Set(['apiKey'])
export const SKILL_MANAGED_KEYS: ReadonlySet<string> = new Set(['agentAccounts'])

/**
 * 子がどれも同じ形（説明だけ違う）の object。提供元・パネル・フッターの項目など。<id> の1行にまとめる。
 * 2つだけ（入力と出力の値段、2つの CLI のモデル）は意味が違うことが多いので、そのまま並べる
 */
function sameShapedChildren(schema: JsonSchema): string[] | null {
  const entries = Object.entries(schema.properties ?? {})
  if (entries.length < 3) return null
  const shape = ({ description: _d, ...rest }: JsonSchema): string => JSON.stringify(rest)
  const first = shape(entries[0][1])
  return entries.every(([, v]) => shape(v) === first) ? entries.map(([k]) => k) : null
}

const escapeRegExp = (text: string): string => text.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')

/**
 * スキーマをたどって、書き換えられる項目を1行ずつ（入れ子は a.b.c、配列の中は a[].b、同じ形の子は a.<id>.b）。
 * スキーマから作るので、設定の項目が増えても減っても skill の表が追従する
 */
function rows(properties: Record<string, JsonSchema>, prefix: string, skip: ReadonlySet<string> = new Set()): string[] {
  const out: string[] = []
  for (const [key, value] of Object.entries(properties)) {
    if (skip.has(key) || SKILL_SECRET_KEYS.has(key)) continue
    const path = `${prefix}${key}`
    if (SKILL_MANAGED_KEYS.has(path)) {
      out.push(`| \`${path}\` | ${typeOf(value)} | Managed by Ferret, do not edit (see above). ${oneLine(value.description)} |`)
      continue
    }
    const ids = sameShapedChildren(value)
    if (ids) {
      const shared = value.properties![ids[0]]
      out.push(`| \`${path}\` | ${typeOf(value)}${detailsOf(value)} | ${oneLine(value.description)} |`)
      const keyWord = new RegExp(`\\b${escapeRegExp(ids[0])}\\b`, 'g')
      const sharedText = oneLine(shared.description).replace(keyWord, '<id>')
      out.push(`| \`${path}.<id>\` | ${typeOf(shared)}${detailsOf(shared)} | <id> is one of ${ids.map((id) => `\`${id}\``).join(', ')}. ${sharedText} |`)
      out.push(...children(shared, `${path}.<id>`))
      continue
    }
    out.push(`| \`${path}\` | ${typeOf(value)}${detailsOf(value)} | ${oneLine(value.description)} |`)
    out.push(...children(value, path))
  }
  return out
}

function children(schema: JsonSchema, path: string): string[] {
  if (schema.properties) return rows(schema.properties, `${path}.`)
  if (schema.type === 'array' && schema.items?.properties) return rows(schema.items.properties, `${path}[].`)
  return []
}

/** SKILL.md の本文。Agent が読む文なので英語（スキーマの説明も英語） */
export function renderAgentSkill(context: SkillContext): string {
  const schema = context.schema ?? SETTINGS_SCHEMA
  const top = schema.properties ?? {}
  const project = top.projects?.items?.properties ?? {}
  const target = project.urls?.items?.properties ?? {}
  // $schema は道具の印、projects はプロジェクトの範囲として別に書く。状態（state.json）は settings.json に無い
  const globalRows = rows(top, '', new Set(['$schema', 'projects', ...STATE_KEYS]))
  const projectRows = rows(project, 'projects[].', new Set(['urls']))
  const targetRows = rows(target, 'projects[].urls[].')
  const secretList = [...SKILL_SECRET_KEYS].map((k) => `\`${k}\``).join(', ')
  const managed = [...SKILL_MANAGED_KEYS].filter((k) => k in top)
  const managedNote = managed.length
    ? `Do not edit ${managed.map((k) => `\`${k}\``).join(', ')} (signed-in agent accounts, managed by Ferret's Accounts section together with their login folders); its fields are not listed. Ask the user to add, switch or remove accounts in Ferret.`
    : ''

  return `---
name: ${AGENT_SKILL_NAME}
description: Change settings of Ferret, the voice-and-annotation review app the user runs next to you (theme, language, layout, panels and footer, terminal, browser extensions, updates, crash reports, agents and usage-limit failover, recording, transcription, organizing, decision model, projects and their review targets such as URLs, launch commands and desktop/mobile/game windows) and drive its orchestra (the All products dashboard: the human.md list of what people must check, infrastructure costs (actual and estimated) in .ferret/costs.json, ready-made requests, products in or out of the orchestra, shared and per-product rules). Use when the user asks to configure, change, turn on/off, add or remove anything "in Ferret", to register a URL, app window, simulator or launch command for a project, or to update the orchestra dashboard, human.md or costs.
---

${SKILL_MARKER}
<!-- Ferret ${context.version} -->

# Ferret settings

Ferret keeps all of its configuration in one JSON file and reloads it live: save the file and the app applies the change within a second. You never need to restart Ferret.

- Settings file: \`${context.settingsPath}\`
- JSON Schema (rewritten by Ferret on every start, always matches the running version): \`${context.schemaPath}\`

## Decide the scope first

Every request is either **global** (the whole app, every project) or **project** (only one registered project). Pick the scope before editing:

1. If the user says "this project", "here", "for <project name>", or the change is about a project's URL, launch command, window, kind or name → **project scope**.
2. Otherwise → **global scope**.
3. If the user asks for a project-only version of something that only exists globally (for example "dark theme only in this project"), do not invent a key. Say that the setting is global in Ferret and ask whether to change it for all projects.

### Global scope

Every setting of the file except projects, generated from the schema: nested keys are written as \`a.b\`, keys inside array items as \`a[].b\`, and \`<id>\` stands for each of the listed keys (providers, panels, footer items, agents). Change only the keys you need and keep everything else as is.

${managedNote}

| Key | Type | Meaning |
| --- | --- | --- |
${globalRows.join('\n')}

### Project scope

Projects are the objects in the top-level \`projects\` array. Find the right one by \`folderPath\`: the project whose \`folderPath\` is your current working directory or contains it. If none matches, ask the user which project they mean, or add a new entry (\`id\` any unique string, \`folderPath\` absolute path). Never change another project's entry.

| Key | Type | Meaning |
| --- | --- | --- |
${projectRows.join('\n')}

Review targets are \`projects[].urls\` (the first one opens by default). Each needs at least one of \`url\`, \`launchCommand\` or \`windowMatch\`. Use \`windowMatch\` for desktop apps, iOS Simulator, Android Emulator or game editors (Unity, Unreal, Godot): Ferret shows that window live in its editor and records it with voice and annotations. Add \`watch: "record"\` (or \`"switch"\` to also show it) when the window is not open yet when recording starts, e.g. a desktop app that the web app launches: Ferret records it as soon as it opens, alongside the current view, and the user switches between the recorded views in the recording bar. \`windowMatch\` may also be a macOS bundle id or an app or executable path.

| Key | Type | Meaning |
| --- | --- | --- |
${targetRows.join('\n')}

## Chrome extensions you are building

When a project builds a Chrome extension, load it into Ferret's built-in browser and keep it current from the terminal, without opening Ferret's settings. Entries live in the global \`browserExtensions\` array (at most ${MAX_BROWSER_EXTENSIONS}); each \`path\` is the absolute path of the unpacked folder that contains manifest.json (the build output such as \`dist/\`, not the source folder when they differ).

- **Register**: build the extension, then add \`{"path": "<absolute folder>"}\` to \`browserExtensions\`. If the same path is already there, do not add it twice.
- **Update to the latest build**: rebuild, then set that entry's \`reload\` to the current Unix time in seconds (any new number works). Ferret loads the extension again from the folder and reloads the open page. Ferret does not watch the folder by itself, so change \`reload\` after every rebuild you want to see.
- **Turn off / remove**: set \`"enabled": false\` to keep it listed but unloaded, or delete the entry to remove it.
- While Ferret is recording it reloads the extension but leaves the open page alone, so the recording is not interrupted. The result (name, version or a load error) shows in Ferret's Settings > Browser extensions.

## Orchestra (All products dashboard)

Ferret's All products view runs one top-level agent over every registered product, with one subagent per product. Its dashboard is built from plain files and settings that you can change directly; it re-reads them every 30 seconds and when the user presses Reload.

- **All products folder**: \`${context.editorWorkspacePath ?? '<Ferret user data>/editor-workspace'}\`. Each registered project appears inside it as a link to its real folder.
- **What people must check** (top of the dashboard): \`human.md\` in the All products folder. Write one row per item in a table \`| No. | Product | URL | What to check |\` (the line after the header must be \`|---|---|---|---|\`). Numbers: B1, B2 … for screens to check, A1 … for approvals, P1 … for things a person must provide, D1 … for decisions. Rows with an http(s) URL get an Open button and are included in the one-recording review; use \`-\` in the URL column when there is none. Unchecked \`- [ ] …\` bullets also count. For a choice, write a question block after the table: a heading \`### Q1 [product] question\`, optional explanation lines, then numbered options \`1. …\` with \`(recommended)\` after the recommended one. The person answers on the dashboard (pick a number or write freely); Ferret stores answers as \`- Q1: 2. …\` lines under \`## Answers\` at the end of human.md and sends them all to the agent at once. Remove rows that are done together with their answer line. Never write secrets.
- **Costs** (infrastructure only — AWS, Cloudflare, Google Cloud, domains, external services; AI subscriptions and agent conversations are not shown): \`.ferret/costs.json\` — in a product's folder for that product, in the All products folder for shared costs. \`items\` are actual costs (this month, this year, total, by product, provider, category and item); \`estimates\` are the resources running now priced per month, with \`checkedAt\` the date you checked: \`{"items":[{"name":"AWS 2026-09 bill","provider":"AWS","category":"infra","usd":41.2,"date":"2026-09-30"},{"name":"Cloudflare Workers Paid","provider":"Cloudflare","category":"infra","monthlyUsd":5,"since":"2026-01"}],"checkedAt":"2026-10-10","estimates":[{"name":"EC2 t3.small ×2","provider":"AWS","monthlyUsd":30.4,"basis":"$0.0208/h × 730h × 2"}]}\`. \`category\` is infra, service or other (ai is ignored); fixed monthly amounts use \`monthlyUsd\` + \`since\` (and \`until\` when they ended, both YYYY-MM); per-bill amounts use \`usd\` + \`date\` (YYYY-MM-DD). Amounts are USD. Without \`estimates\`, the estimate uses the monthly items still active.
- **Products in or out**: set \`projects[].orchestraExcluded: true\` to leave a product out of the orchestra (no subagent, not in reviews or requests); remove it to bring the product back.
- **Browser sign-ins**: the built-in browser shares sign-ins (Google, Gmail, GitHub…) across every project. To keep a project apart (another client), set \`projects[].browserProfile\` to a group name; projects with the same name share sign-ins with each other only. Remove it to share again.
- **Allowed without asking**: \`orchestra.allowed\` lists, one per line, operations agents may do without a person's check (for example \`deploy to the dev environment\`). Also editable at the top of the dashboard.
- **Rules**: \`orchestra.shared\` (rules for every product) and \`orchestra.products.<project id>\` (rules for one product). Ferret writes them into the All products CLAUDE.md / AGENTS.md and each product's subagent.
- **Ready-made requests** (the Requests list on the dashboard): \`agentRequests.items\`. Change a built-in request's \`text\`, add your own with \`custom: true\` + \`title\` + \`text\` (any id such as \`custom-weekly-report\`), and set \`hidden: true\` on one-time requests that are done (for example \`sentry-setup\`, \`analytics-setup\`, \`search-console\`, \`infra\`). People send them from the dashboard; you do not need to send them yourself.
- **Feedback from one recording across products**: reviews recorded in All products are split by the page URL of each finding; each product's own agent gets its findings directly, and the rest come to the top-level agent with the product named. When you get such a request, run the products in parallel through their subagents, and inside each product run independent work in parallel too.
- **Interrupted work**: when Ferret was closed or the computer slept in the middle of a request, Ferret reopens the conversation and asks you to continue. Check what is already done (git status, files, the last report) before continuing, and do not redo finished steps.

## How to edit

1. Read the settings file. If it does not exist yet, create it with only the keys you set (Ferret fills in the defaults).
2. Read the JSON Schema file when you need more detail (patterns, maximum lengths, defaults of whole objects) than the tables show.
3. Make the smallest change: keep unknown keys, key order and the other projects untouched. Write valid JSON (no comments, no trailing commas).
4. Do not write API keys or tokens into the file. The plaintext ${secretList} fields are left out of this skill on purpose; never set them, even if the user pastes a key. Secret HTTP headers are only accepted as \`{"env": "VAR_NAME"}\`. Use the \`apiKeyEnv\` fields (the name of an environment variable, or a key in \`~/.ferret/.env\` or the project's \`.env\`), or ask the user to paste the key in Ferret's Settings page.
5. Do not edit \`state.json\` next to the settings file (window state kept by the app).
6. After saving, tell the user what you changed and in which scope. If Ferret rejects the file it shows the error in the app and keeps the previous settings; fix the file using the schema.
`
}
