/**
 * オーケストレーター：プロジェクトのすぐ下のフォルダを子のプロジェクトとして束ねる。
 * 人は親のフォルダで動く Claude Code に頼み、親は子ごとの subagent（<親>/.claude/agents/ferret-<子>.md）に作業を任せる。
 * レビューも親に集まり、送ると親の Agent がどの子のものかを見分けて任せる（複数のプロジェクトを行き来しなくてよい）。
 *
 * Ferret が書いた subagent には印（SUBAGENT_MARKER）を入れ、印のあるものだけを書き直す・消す（利用者が置いた同じ名前のものは触らない）。
 * Electron に依存しない純粋な処理だけを置く（書き込みは src/main/orchestrator.ts）。
 */

export const SUBAGENT_PREFIX = 'ferret-'

/** Ferret が書いた印。この行があるものだけを Ferret のものとして書き直す・消す */
export const SUBAGENT_MARKER = '<!-- ferret-orchestrator: generated by Ferret for this project folder. Ferret rewrites or removes this file; local edits are overwritten. -->'

export function isFerretSubagent(text: string): boolean {
  return text.includes(SUBAGENT_MARKER)
}

/** 子として見ないフォルダ（隠しフォルダは別に外す） */
const SKIPPED_DIRS = new Set(['node_modules', 'dist', 'build', 'out', 'target', 'vendor'])

export interface ChildEntry {
  /** 親のすぐ下のフォルダの名前 */
  name: string
  /** そのフォルダに .git がある（ファイルでもよい。worktree・submodule） */
  isGitRepo: boolean
}

export interface OrchestratorChild {
  /** 親からの相対パス（すぐ下のフォルダの名前） */
  dir: string
  /** 表示名。登録済みのプロジェクトならその名前 */
  name: string
  /** subagent の名前（ferret-<英数字>） */
  agent: string
}

/**
 * 親のすぐ下で、子のプロジェクトにするフォルダ。git のリポジトリか、Ferret に登録済みのプロジェクトのフォルダ。
 * 並びはフォルダの名前の順。subagent の名前は重ならないよう番号を付ける
 */
export function orchestratorChildren(
  parentFolder: string,
  entries: readonly ChildEntry[],
  registered: ReadonlyArray<{ folderPath: string; name: string }>,
  join: (...parts: string[]) => string
): OrchestratorChild[] {
  const byFolder = new Map(registered.map((p) => [normalizeFolder(p.folderPath), p.name]))
  const used = new Set<string>()
  return [...entries]
    .filter((e) => e.name && !e.name.startsWith('.') && !SKIPPED_DIRS.has(e.name))
    .sort((a, b) => a.name.localeCompare(b.name))
    .flatMap((e) => {
      const projectName = byFolder.get(normalizeFolder(join(parentFolder, e.name)))
      if (!e.isGitRepo && projectName === undefined) return []
      const base = `${SUBAGENT_PREFIX}${slug(e.name)}`
      let agent = base
      for (let n = 2; used.has(agent); n++) agent = `${base}-${n}`
      used.add(agent)
      return [{ dir: e.name, name: projectName || e.name, agent }]
    })
}

/** 比べるための形。区切りを / にそろえ、Windows のドライブのパス（大文字・小文字を区別しない）は小文字にする */
function normalizeFolder(path: string): string {
  const p = path.replace(/\\/g, '/').replace(/\/+$/, '')
  return /^[a-z]:\//i.test(p) ? p.toLowerCase() : p
}

/** subagent の名前に使える形（小文字の英数字とハイフン）。日本語だけの名前などは project */
export function slug(name: string): string {
  const s = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40).replace(/-+$/, '')
  return s || 'project'
}

/** 1行に収める（frontmatter の値を壊さない） */
function oneLine(text: string): string {
  return text.replace(/[\r\n]+/g, ' ').replace(/"/g, "'").trim()
}

/** <親>/.claude/agents/<agent>.md の中身（Claude Code の subagent） */
export function renderSubagent(child: OrchestratorChild, parentFolder: string, join: (...parts: string[]) => string): string {
  const abs = join(parentFolder, child.dir)
  const name = oneLine(child.name)
  return [
    '---',
    `name: ${child.agent}`,
    `description: "Works in the ${name} project (folder ${oneLine(child.dir)}/). Use it for any request, bug, review finding, or file that concerns ${name} or paths under ${oneLine(child.dir)}/."`,
    '---',
    SUBAGENT_MARKER,
    '',
    `You work only inside the ${name} project: \`${abs}\`.`,
    '',
    `- Before changing anything, read \`${child.dir}/CLAUDE.md\` or \`${child.dir}/AGENTS.md\` if present and follow them.`,
    `- Run commands from that folder (\`cd "${abs}"\` first). Do not edit files outside it. If the task also needs changes in another project, say so in your report instead of making them.`,
    '- When the task is a Ferret review finding, the request names the review folder (`.ferret/reviews/<id>/`). Fix only the findings that belong to this project and record each one\'s status in that review\'s `progress.json` as the request describes.',
    '- End with a short report: what you changed (files), how you checked it, and anything left for the orchestrator.',
    ''
  ].join('\n')
}

export interface SubagentFile {
  /** ファイル名（<agent>.md） */
  file: string
  text: string
}

export interface SubagentPlan {
  write: SubagentFile[]
  /** 消す Ferret のファイル（子でなくなった・オーケストレーターをやめた） */
  remove: string[]
  /** 同じ名前で Ferret のものでないファイルがあるので書かない */
  skipped: string[]
}

/**
 * 今ある .claude/agents のファイル（ferret- で始まるもの）と、書きたい中身から、書く・消す・飛ばすを決める。
 * want が空ならオーケストレーターをやめたとき（Ferret のものを全部消す）
 */
export function planSubagents(existing: ReadonlyArray<{ file: string; text: string | null }>, want: readonly SubagentFile[]): SubagentPlan {
  const current = new Map(existing.map((e) => [e.file, e.text]))
  const wanted = new Set(want.map((w) => w.file))
  const write: SubagentFile[] = []
  const skipped: string[] = []
  for (const w of want) {
    if (!current.has(w.file)) { write.push(w); continue }
    const text = current.get(w.file)
    // 読めない（リンクなど）・印が無いものは利用者のもの
    if (text === null || text === undefined || !isFerretSubagent(text)) { skipped.push(w.file); continue }
    if (text !== w.text) write.push(w)
  }
  const remove = existing.filter((e) => !wanted.has(e.file) && e.text !== null && isFerretSubagent(e.text)).map((e) => e.file)
  return { write, remove, skipped }
}

/** 子の一覧を、送る指示文に足す1行の形にする（例 `Shop (shop/) → ferret-shop`） */
export function childList(children: readonly OrchestratorChild[]): string {
  return children.map((c) => `${c.name} (${c.dir}/) → ${c.agent}`).join(', ')
}
