/**
 * オーケストレーター：プロジェクトのすぐ下のフォルダを子のプロジェクトとして束ねる。
 * 人は親のフォルダで動く Claude Code に頼み、親は子ごとの subagent（<親>/.claude/agents/ferret-<子>.md）に作業を任せる。
 * レビューも親に集まり、送ると親の Agent がどの子のものかを見分けて任せる（複数のプロジェクトを行き来しなくてよい）。
 *
 * Ferret が書いた subagent には印（SUBAGENT_MARKER）を入れ、印のあるものだけを書き直す・消す（利用者が置いた同じ名前のものは触らない）。
 * Electron に依存しない純粋な処理だけを置く（書き込みは src/main/orchestrator.ts）。
 */

export const SUBAGENT_PREFIX = 'ferret-'

/** Ferret が書いた印。この行があるものだけを Ferret のものとして書き直す・消す */
export const SUBAGENT_MARKER = '<!-- ferret-orchestrator: generated by Ferret for this project folder. Ferret rewrites or removes this file; local edits are overwritten. -->'

export function isFerretSubagent(text: string): boolean {
  return text.includes(SUBAGENT_MARKER)
}

/** 子として見ないフォルダ（隠しフォルダは別に外す） */
const SKIPPED_DIRS = new Set(['node_modules', 'dist', 'build', 'out', 'target', 'vendor'])

export interface ChildEntry {
  /** 親のすぐ下のフォルダの名前 */
  name: string
  /** そのフォルダに .git がある（ファイルでもよい。worktree・submodule） */
  isGitRepo: boolean
}

export interface OrchestratorChild {
  /** 表示と指示文に使う場所。親の下なら相対パス（フォルダの名前）、入れた既存のプロジェクトなら絶対パス */
  dir: string
  /** Agent が作業するフォルダの絶対パス（入れたプロジェクトはメインフォルダの下のリンク） */
  path: string
  /** 入れたプロジェクトの本当のフォルダ（メインフォルダの外。Claude Code の additionalDirectories に足す） */
  outside?: string
  /** 登録したプロジェクトの id（プロダクトごとのルールを引く） */
  projectId?: string
  /** そのプロジェクトの確認先の URL（Web・デザイン・設計）。全体のフィードバックの指摘をどのプロジェクトに任せるかの手がかり */
  urls?: string[]
  /** 表示名。登録済みのプロジェクトならその名前 */
  name: string
  /** subagent の名前（ferret-<英数字>） */
  agent: string
}

/**
 * 親のすぐ下で、子のプロジェクトにするフォルダ。git のリポジトリか、Ferret に登録済みのプロジェクトのフォルダ。
 * 並びはフォルダの名前の順。subagent の名前は重ならないよう番号を付ける
 */
export function orchestratorChildren(
  parentFolder: string,
  entries: readonly ChildEntry[],
  registered: ReadonlyArray<{ folderPath: string; name: string }>,
  join: (...parts: string[]) => string
): OrchestratorChild[] {
  const byFolder = new Map(registered.map((p) => [normalizeFolder(p.folderPath), p.name]))
  const used = new Set<string>()
  return [...entries]
    .filter((e) => e.name && !e.name.startsWith('.') && !SKIPPED_DIRS.has(e.name))
    .sort((a, b) => a.name.localeCompare(b.name))
    .flatMap((e) => {
      const projectName = byFolder.get(normalizeFolder(join(parentFolder, e.name)))
      if (!e.isGitRepo && projectName === undefined) return []
      const base = `${SUBAGENT_PREFIX}${slug(e.name)}`
      let agent = base
      for (let n = 2; used.has(agent); n++) agent = `${base}-${n}`
      used.add(agent)
      return [{ dir: e.name, path: join(parentFolder, e.name), name: projectName || e.name, agent }]
    })
}

/**
 * 子のプロジェクトの全体。オーケストレーターに入れた既存のプロジェクト（members。フォルダはどこでもよい）と、
 * 親のすぐ下のフォルダのプロジェクト。同じフォルダは1つにし、subagent の名前は重ならないよう番号を付ける。
 * SSH のプロジェクト（手元にフォルダが無い）・消えたプロジェクト・自分自身は入れない
 */
export function allOrchestratorChildren(
  parentFolder: string,
  members: readonly string[],
  registered: ReadonlyArray<{ id: string; folderPath: string; name: string; source?: string; urls?: ReadonlyArray<{ url?: string }> }>,
  subfolders: readonly OrchestratorChild[],
  /** 入れたプロジェクトの id → メインフォルダの下に作ったリンクの名前（作れなかったものは無い） */
  links: ReadonlyMap<string, string> = new Map(),
  join: (...parts: string[]) => string = (...parts) => parts.join('/')
): OrchestratorChild[] {
  const seen = new Set(subfolders.map((c) => normalizeFolder(c.path)))
  seen.add(normalizeFolder(parentFolder))
  const used = new Set(subfolders.map((c) => c.agent))
  const added: OrchestratorChild[] = []
  for (const id of members) {
    const project = registered.find((p) => p.id === id)
    if (!project || project.source === 'ssh' || seen.has(normalizeFolder(project.folderPath))) continue
    seen.add(normalizeFolder(project.folderPath))
    const base = `${SUBAGENT_PREFIX}${slug(project.name || folderName(project.folderPath))}`
    let agent = base
    for (let n = 2; used.has(agent); n++) agent = `${base}-${n}`
    used.add(agent)
    const link = links.get(id)
    const urls = (project.urls ?? []).flatMap((u) => (u.url ? [u.url] : [])).slice(0, 8)
    added.push({
      ...(link ? { dir: link, path: join(parentFolder, link) } : { dir: project.folderPath, path: project.folderPath }),
      outside: project.folderPath, projectId: id, name: project.name || folderName(project.folderPath), agent,
      ...(urls.length ? { urls } : {})
    })
  }
  return [...subfolders, ...added]
}

function folderName(path: string): string {
  return path.replace(/[\\/]+$/, '').split(/[\\/]/).pop() ?? path
}

/** 子のフォルダのうち、親の外にあるもの（Claude Code の additionalDirectories に足す） */
export function outsideFolders(children: readonly OrchestratorChild[]): string[] {
  return children.flatMap((c) => (c.outside ? [c.outside] : []))
}

/** メインフォルダの下に作るリンクの名前（フォルダの名前。使えない文字は - に。重なれば番号） */
export function memberLinkName(folderPath: string, taken: ReadonlySet<string>): string {
  const base = (folderName(folderPath).replace(/[<>:"|?*\u0000-\u001f]/g, '-').replace(/^\.+/, '').trim() || 'project').slice(0, 80)
  let name = base
  for (let n = 2; taken.has(name.toLowerCase()); n++) name = `${base}-${n}`
  return name
}

/** 比べるための形。区切りを / にそろえ、Windows のドライブのパス（大文字・小文字を区別しない）は小文字にする */
function normalizeFolder(path: string): string {
  const p = path.replace(/\\/g, '/').replace(/\/+$/, '')
  return /^[a-z]:\//i.test(p) ? p.toLowerCase() : p
}

/** subagent の名前に使える形（小文字の英数字とハイフン）。日本語だけの名前などは project */
export function slug(name: string): string {
  const s = name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40).replace(/-+$/, '')
  return s || 'project'
}

/** 1行に収める（frontmatter の値を壊さない） */
function oneLine(text: string): string {
  return text.replace(/[\r\n]+/g, ' ').replace(/"/g, "'").trim()
}

/** <親>/.claude/agents/<agent>.md の中身（Claude Code の subagent） */
/** 人が Ferret の設定に書いた、共通のルールとプロダクトごとのルール（設定の「オーケストラ」） */
export interface OrchestraRules {
  shared?: string
  /** 全体として人の確認なしで進めてよい操作（1行に1つ。例：dev 環境へのデプロイ） */
  allowed?: string
  /** プロジェクトの id → そのプロダクトだけのルール（インフラ・タグ・インスタンスなど） */
  products?: Record<string, string>
}

const ALLOWED_TITLE = 'Operations allowed without asking a person (set by the human in Ferret; do them without adding them to human.md):'

function rulesBlock(title: string, text: string | undefined): string[] {
  const body = text?.trim()
  return body ? ['', title, '', body] : []
}

export function renderSubagent(child: OrchestratorChild, rules?: OrchestraRules): string {
  const abs = child.path
  const name = oneLine(child.name)
  return [
    '---',
    `name: ${child.agent}`,
    `description: "Lead for the ${name} project (folder ${oneLine(child.dir)}/${child.urls?.length ? `; pages ${child.urls.map(oneLine).join(', ')}` : ''}). Use it for any request, bug, review finding, page or file that concerns ${name}${child.urls?.length ? ' or those URLs' : ''} or paths under ${oneLine(child.dir)}/."`,
    '---',
    SUBAGENT_MARKER,
    '',
    `You lead the ${name} project: \`${abs}\`. A project may be software or a business (blog, YouTube, ads, sales, data analysis); work the way its own files describe.`,
    '',
    '- You are the second level of three. The orchestrator (first level) gives you this project\'s part; you plan it and, when it is large, split it into independent pieces and run each piece as a third-level worker in this project\'s folder, in parallel: `cd "' + abs + '" && claude -p "<one piece, with the shared and project rules it must follow>"` (run them in the background and wait for all). Each worker uses this project\'s own CLAUDE.md, skills and subagents. Small tasks you do yourself.',
    '- Check every worker\'s result before reporting; nothing goes back to the orchestrator unverified.',
    `- Before changing anything, read \`${abs}/CLAUDE.md\` or \`${abs}/AGENTS.md\` if present and follow them, together with the shared rules the orchestrator gives you.`,
    `- Run commands from that folder (\`cd "${abs}"\` first). Do not edit files outside it. If the task also needs changes in another project, say so in your report instead of making them.`,
    '- When the task is a Ferret review finding, the request names the review folder (`.ferret/reviews/<id>/`). Fix only the findings that belong to this project and record each one\'s status in that review\'s `progress.json` as the request describes.',
    '- Use the tools, connections and permissions this session already has (Claude in Chrome and other browser use, computer use, MCP servers, logins). Do not start a new connection or ask the user to approve again; if something is missing, report it to the orchestrator instead.',
    '- Browser work (Claude in Chrome, computer use) runs at the same time as the other products\' subagents: open your own tab or window for this product and never wait for another product to finish with the browser.',
    '- End with a short report: what you changed (files), how you checked it, and anything left for the orchestrator.',
    ...rulesBlock(ALLOWED_TITLE, rules?.allowed),
    ...rulesBlock('Shared rules for all products (set by the human in Ferret):', rules?.shared),
    ...rulesBlock(`Rules only for ${name} (set by the human in Ferret; infrastructure and other per-product settings):`, child.projectId ? rules?.products?.[child.projectId] : undefined),
    ''
  ].join('\n')
}

export interface SubagentFile {
  /** ファイル名（<agent>.md） */
  file: string
  text: string
}

export interface SubagentPlan {
  write: SubagentFile[]
  /** 消す Ferret のファイル（子でなくなった・オーケストレーターをやめた） */
  remove: string[]
  /** 同じ名前で Ferret のものでないファイルがあるので書かない */
  skipped: string[]
}

/**
 * 今ある .claude/agents のファイル（ferret- で始まるもの）と、書きたい中身から、書く・消す・飛ばすを決める。
 * want が空ならオーケストレーターをやめたとき（Ferret のものを全部消す）
 */
export function planSubagents(existing: ReadonlyArray<{ file: string; text: string | null }>, want: readonly SubagentFile[]): SubagentPlan {
  const current = new Map(existing.map((e) => [e.file, e.text]))
  const wanted = new Set(want.map((w) => w.file))
  const write: SubagentFile[] = []
  const skipped: string[] = []
  for (const w of want) {
    if (!current.has(w.file)) { write.push(w); continue }
    const text = current.get(w.file)
    // 読めない（リンクなど）・印が無いものは利用者のもの
    if (text === null || text === undefined || !isFerretSubagent(text)) { skipped.push(w.file); continue }
    if (text !== w.text) write.push(w)
  }
  const remove = existing.filter((e) => !wanted.has(e.file) && e.text !== null && isFerretSubagent(e.text)).map((e) => e.file)
  return { write, remove, skipped }
}

/** 子の一覧を、送る指示文に足す1行の形にする（例 `Shop (shop/) → ferret-shop`） */
export function childList(children: readonly OrchestratorChild[]): string {
  return children.map((c) => `${c.name} (${c.dir}/) → ${c.agent}`).join(', ')
}

// ───────────── CLAUDE.md / AGENTS.md の Ferret の欄 ─────────────

export const GUIDE_START = '<!-- ferret-orchestrator:start (generated by Ferret; edits inside this block are overwritten) -->'
export const GUIDE_END = '<!-- ferret-orchestrator:end -->'

/**
 * オーケストレーターのフォルダの CLAUDE.md・AGENTS.md に入れる Ferret の欄。
 * 1つの Agent とのやり取りで、共通の部分は1回で決め、プロダクトごとの部分は子の subagent に並行して任せる進め方を書く
 */
export function renderOrchestratorGuide(children: readonly OrchestratorChild[], rules?: OrchestraRules): string {
  const list = children.length
    ? children.map((c) => `- ${oneLine(c.name)}: \`${c.path}\` (subagent: \`${c.agent}\`)`).join('\n')
    : '- (no products yet. Add projects to this orchestrator in Ferret.)'
  return [
    GUIDE_START,
    '## Orchestrator (managed by Ferret)',
    '',
    'This folder coordinates several products that are developed in parallel. Each product is its own project and has a subagent:',
    '',
    list,
    '',
    'How to work on a request:',
    '',
    '1. Split it into shared work and per-product work. Shared work is anything several products must agree on: conventions, API contracts, data models, shared libraries, design tokens, docs. Decide it once, write the decision in the "Shared rules" section of this file (outside this block), and do shared code changes once, in the product or shared package that owns it, before the per-product work. Keep separate what must stay separate per product: infrastructure (cloud accounts, deployments, databases, secrets and environment variables, CI/CD, domains, billing), each product\'s data, and its release timing. Never merge or share these across products unless the user asks for it.',
    '2. Hand each product\'s part to that product\'s subagent, one task per product, and start the tasks for independent products together (several Task calls in one message) so they run in parallel. Tell each subagent the shared rules it must follow.',
    '3. Subagents work only in their own folders and report back. Check the reports for consistency across products, fix any mismatch, and summarize for the user per product.',
    '4. Ferret reviews can cover many products in one recording. Each finding names its product by URL, screen or file path (each subagent\'s description lists its pages). Route each finding to its product\'s subagent; findings for different products run in parallel.',
    '5. Work in three levels: you (orchestra) → one subagent per product (its lead) → workers the lead starts inside that product\'s folder for independent pieces. A product can be software or a business (blog, YouTube, ads, sales outreach, data analysis); the lead works the way that product\'s own files describe.',
    '6. Anything that needs a person (a decision, a login, a value check, an approval) goes into human.md in this folder as a table row: | # | product | URL | what to check | (B1… screens, A1… approvals, P1… things to provide, D1… decisions). Make every item multiple choice: after the table, add a block with the same number (Q1… for questions not in the table): a heading `### P2 [product] question`, optional explanation lines, then 2–4 numbered options `1. …`, the recommended one first with `(recommended)` after it; the block runs until the next heading. Always name the product. The person picks an option (and can add a note) in Ferret, which writes `- P2: 1. … — note` lines under `## Answers` at the end of human.md; never remove an answer line before you have acted on it. Keep one row per thing, update it when the state changes, and delete it together with its answer once it is done. Do not put the operations allowed without asking (below) into human.md; just do them. Ferret shows human.md as a checklist and lets the person open every URL in one feedback session.',
    '7. Connections and permissions are set up once, here at the top: Claude in Chrome and other browser use, computer use, MCP servers, logins, and permission approvals. Subagents inherit this session\'s tools and approvals, so never set them up again per product and never ask the user to connect or approve again for each product.',
    '8. Security, tests and anything else that must not be missed: run them for every included product in parallel, each with an independent second check, and treat an unchecked product as not done.',
    '9. Every request that reaches you here runs as parallel subagents, one per product, all started together, including browser use (Claude in Chrome, computer use): each subagent works in its own tab or window at the same time. Never run products one after another; a person who wants a serial run asks inside that product instead.',
    '10. Without subagents (for example Codex), do the same steps yourself, working in each product\'s folder in turn.',
    ...rulesBlock(`### ${ALLOWED_TITLE}`, rules?.allowed),
    ...rulesBlock('### Shared rules (set by the human in Ferret)', rules?.shared),
    ...children.flatMap((c) => rulesBlock(`### Rules only for ${oneLine(c.name)} (set by the human in Ferret)`, c.projectId ? rules?.products?.[c.projectId] : undefined)),
    GUIDE_END
  ].join('\n')
}

/**
 * Ferret の欄を差し替えた中身。無ければ末尾に足す。ファイルが無ければ欄と tail（人が書く部分の雛形）で作る。同じなら null。
 * 人が書く部分は作るときの雛形だけで、そのあとは触らない
 */
export function withGuideBlock(existing: string | null, block: string, tail = ''): string | null {
  if (existing === null) return `${block}\n${tail ? `\n${tail.replace(/\s*$/, '')}\n` : ''}`
  const start = existing.indexOf(GUIDE_START)
  const end = existing.indexOf(GUIDE_END, start + 1)
  const next = start >= 0 && end > start
    ? existing.slice(0, start) + block + existing.slice(end + GUIDE_END.length)
    : `${existing.replace(/\s*$/, '')}\n\n${block}\n`
  return next === existing ? null : next
}

/** Ferret の欄を外した中身（やめたとき）。欄が無ければ null */
export function withoutGuideBlock(existing: string | null): string | null {
  if (existing === null) return null
  const start = existing.indexOf(GUIDE_START)
  const end = existing.indexOf(GUIDE_END, start + 1)
  if (start < 0 || end < start) return null
  const before = existing.slice(0, start).replace(/\s*$/, '')
  const after = existing.slice(end + GUIDE_END.length).replace(/^\s*/, '')
  const rest = [before, after].filter(Boolean).join('\n\n')
  return rest ? `${rest.replace(/\s*$/, '')}\n` : ''
}

// ───────────── .claude/settings.local.json の additionalDirectories ─────────────

/**
 * Claude Code が子のフォルダ（親の外）を読み書きできるよう、permissions.additionalDirectories を合わせる。
 * 利用者が書いた値は残し、前回 Ferret が足したもの（managed）だけを入れ替える。読めない JSON は書き換えない（null）。
 * 変わらなければ null
 */
export function withAdditionalDirectories(settingsText: string | null, previouslyManaged: readonly string[], wanted: readonly string[]): string | null {
  let settings: Record<string, unknown> = {}
  if (settingsText !== null && settingsText.trim()) {
    try {
      const parsed: unknown = JSON.parse(settingsText)
      if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) return null
      settings = parsed as Record<string, unknown>
    } catch {
      return null
    }
  }
  const permissions = settings.permissions && typeof settings.permissions === 'object' && !Array.isArray(settings.permissions) ? settings.permissions as Record<string, unknown> : {}
  const current = Array.isArray(permissions.additionalDirectories) ? permissions.additionalDirectories.filter((d): d is string => typeof d === 'string') : []
  const managed = new Set(previouslyManaged)
  const next = [...current.filter((d) => !managed.has(d)), ...wanted.filter((d) => !current.includes(d) || managed.has(d))]
  const unique = [...new Set(next)]
  if (unique.length === current.length && unique.every((d, i) => d === current[i])) return null
  const nextPermissions = { ...permissions }
  if (unique.length) nextPermissions.additionalDirectories = unique
  else delete nextPermissions.additionalDirectories
  const nextSettings = { ...settings }
  if (Object.keys(nextPermissions).length) nextSettings.permissions = nextPermissions
  else delete nextSettings.permissions
  return `${JSON.stringify(nextSettings, null, 2)}\n`
}

// ───────────── 人が書く部分の雛形（CLAUDE.md・AGENTS.md・README.md を最初に作るとき） ─────────────

export type GuideLanguage = 'ja' | 'en'

/** CLAUDE.md の人が書く部分：共通のルールと、プロダクトごとのルール（作った時点の子の見出し付き） */
export function rulesTemplate(children: readonly OrchestratorChild[], lang: GuideLanguage): string {
  const heads = children.map((c) => `### ${oneLine(c.name)}\n\n- `).join('\n\n')
  return lang === 'ja'
    ? ['## 共通のルール（すべてのプロダクト）', '', '<!-- 全プロダクトで揃えること（規約・API の約束・デザイン・ドキュメントなど）を人が書きます。Agent はこれに従い、共通の決定もここに追記します。 -->', '- ', '', '## プロダクトごとのルール', '', '<!-- プロダクトごとに分けること（インフラ・デプロイ・DB・秘密情報・リリースの時期など）を見出しの下に書きます。見出しはプロダクトの名前です。 -->', '', heads].join('\n')
    : ['## Shared rules (all products)', '', '<!-- What all products must agree on (conventions, API contracts, design, docs). The agent follows these and adds shared decisions here. -->', '- ', '', '## Per-product rules', '', '<!-- What stays separate per product (infrastructure, deployment, databases, secrets, release timing). One heading per product name. -->', '', heads].join('\n')
}

/** AGENTS.md の人が書く部分：ルールは CLAUDE.md の1か所に書く */
export function agentsTemplate(lang: GuideLanguage): string {
  return lang === 'ja'
    ? '共通のルールとプロダクトごとのルールは、このフォルダの CLAUDE.md にあります。作業の前に必ず読み、それに従ってください。'
    : 'The shared rules and the per-product rules are in CLAUDE.md in this folder. Read it before any work and follow it.'
}

/** README.md の Ferret の欄（人向け：プロダクトの一覧） */
export function renderReadmeBlock(children: readonly OrchestratorChild[], lang: GuideLanguage): string {
  const list = children.length
    ? children.map((c) => `- **${oneLine(c.name)}**: \`${c.path}\``).join('\n')
    : (lang === 'ja' ? '- （まだありません。Ferret のサイドバーでプロジェクトを入れます）' : '- (None yet. Put projects under this orchestrator from the Ferret sidebar.)')
  return [GUIDE_START, lang === 'ja' ? '## プロダクト' : '## Products', '', list, GUIDE_END].join('\n')
}

/** README.md の人が書く部分（使い方） */
export function readmeTemplate(name: string, lang: GuideLanguage): string {
  return lang === 'ja'
    ? [`# ${oneLine(name)}`, '', '複数のプロダクトを1つの Agent で並行して開発するためのフォルダ（Ferret のオーケストレーター）です。', '', '- このフォルダで Claude Code に頼むと、共通の部分を先に決め、プロダクトごとの部分をそれぞれの subagent に並行して任せます。', '- 共通の指示とプロダクトごとの指示は **CLAUDE.md** に書きます（AGENTS.md は CLAUDE.md を読むよう Agent に伝えるだけです）。', '- インフラ・デプロイ・DB・秘密情報など、プロダクトごとに分けるものは「プロダクトごとのルール」に書きます。', '- Chrome・computer use・MCP・ログインなどの接続と許可は、このフォルダの Agent で1回だけ済ませます。subagent はそれを使います。', '- `.claude/agents/ferret-*.md` と、各ファイルの `ferret-orchestrator` の印の間は Ferret が書き直します。'].join('\n')
    : [`# ${oneLine(name)}`, '', 'A folder for developing several products in parallel with one agent (a Ferret orchestrator).', '', '- Ask Claude Code in this folder: it settles the shared part first, then hands each product\'s part to that product\'s subagent in parallel.', '- Write shared and per-product instructions in **CLAUDE.md** (AGENTS.md only tells agents to read CLAUDE.md).', '- Infrastructure, deployment, databases, secrets and anything else that stays separate per product go under "Per-product rules".', '- Connections and permissions (Chrome, computer use, MCP, logins) are set up once with the agent in this folder; subagents use them.', '- Ferret rewrites `.claude/agents/ferret-*.md` and the part of each file between the `ferret-orchestrator` markers.'].join('\n')
}

const MAX_RULE_CHARS = 8000

export function sanitizeOrchestraRules(raw: unknown): OrchestraRules | undefined {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) return undefined
  const r = raw as OrchestraRules
  const shared = typeof r.shared === 'string' && r.shared.trim() ? r.shared.slice(0, MAX_RULE_CHARS) : undefined
  const allowed = typeof r.allowed === 'string' && r.allowed.trim() ? r.allowed.slice(0, MAX_RULE_CHARS) : undefined
  const products = r.products && typeof r.products === 'object' && !Array.isArray(r.products)
    ? Object.fromEntries(Object.entries(r.products).filter((e): e is [string, string] => /^[\w-]{1,128}$/.test(e[0]) && typeof e[1] === 'string' && e[1].trim() !== '').slice(0, 200).map(([k, v]) => [k, v.slice(0, MAX_RULE_CHARS)]))
    : {}
  if (!shared && !allowed && !Object.keys(products).length) return undefined
  return { ...(shared ? { shared } : {}), ...(allowed ? { allowed } : {}), ...(Object.keys(products).length ? { products } : {}) }
}
